-- Database: webhook_manager_db

-- DROP DATABASE IF EXISTS webhook_manager_db;

CREATE DATABASE webhook_manager_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Table: public.webhook_events

-- DROP TABLE IF EXISTS public.webhook_events;

CREATE TABLE IF NOT EXISTS public.webhook_events
(
    request_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    target_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    source_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_id bigint NOT NULL,
    payload text COLLATE pg_catalog."default",
    CONSTRAINT webhook_events_pkey PRIMARY KEY (request_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.webhook_events
    OWNER to postgres;